# Teams, Players and Fixtures keys
FPL_FIXTURES = {
    "id": 0,
    "name": "",
    "deadline_time": "",
    "is_current": "bool",
    "is_previous": "bool",
    "is_next": "bool",
    "finished": "bool",
    "data_checked": "bool",
    "highest_score": 0,
    "most_selected": 0,
    "most_transferred_in": 0,
    "top_element": 0,
    "top_element_info": {
        "id": 0,
        "points": 0,
    },
    "most_captained": 0,
    "most_vice_captained": 0,
}

FIXTURES = {
    "event": 0,
    "finished": "bool",
    "id": 0,
    "kickoff_time": "2025-08-15T19:00:00Z",
    "started": "true",
    "team_a": "4",
    "team_a_score": "2",
    "team_h": "12",
    "team_h_score": "4",
    "stats": {
        "goals_scored": {
            "a": [],
            "h": [],
        },
        "assists": {
            "a": [],
            "h": [],
        },
        "own_goals": {
            "a": [],
            "h": [],
        },
        "penalties_saved": {
            "a": [],
            "h": [],
        },
        "penalties_missed": {
            "a": [],
            "h": [],
        },
        "yellow_cards": {
            "a": [],
            "h": [],
        },
        "red_cards": {
            "a": [],
            "h": [],
        },
        "saves": {
            "a": [],
            "h": [],
        },
        "bonus": {
            "a": [],
            "h": [],
        },
        "bps": {
            "a": [],
            "h": [],
        },
        "defensive_contribution": {
            "a": [],
            "h": [],
        },
    },
}

TEAMS = {
    "name": "",
    "short_name": "",
    "tid": 0,
    "table": {
        "win": 0,
        "draw": 0,
        "loss": 0,
        "played": 0,
        "points": 0,
        "position": 0,
        "goals": 0,
        "conceded": 0,
        "form": "",
        "next": "name",
    },
    "expected": {
        "xg": 0,
        "xg_difference": 0,
        "xga": 0,
        "xga_difference": 0,
        "xpts": 0,
        "xpts_difference": 0,
    },
    "strength": {
        "strength": 0,
        "strength_overall_home": 0,
        "strength_overall_away": 0,
        "strength_attack_home": 0,
        "strength_attack_away": 0,
        "strength_defence_home": 0,
        "strength_defence_away": 0,
    },
}

PLAYERS = {
    "id": "",
    "team_code": "",
    "now_cost": 0,
    "web_name": "",
    "total_points": 0,
    "status": "",
    "form": "",
    "element_type": "",
    "stats": {
        "minutes": 0,
        "goals_scored": 0,
        "assists": 0,
        "clean_sheets": 0,
        "goals_conceded": 0,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "recoveries": 0,
        "tackles": 0,
        "saves": 0,
        "clearances_blocks_interceptions": 0,
        "defensive_contribution": 0,
        "starts": 0,
        "influence": 0,
        "creativity": 0,
        "threat": 0,
        "corners_and_indirect_freekicks_order": "",
        "direct_freekicks_order": "",
        "penalties_order": "",
    },
    "fpl_stats": {
        "value_form": 0,
        "value_season": 0,
        "bonus": 0,
        "bps": 0,
        "ict_index": 0,
        "event_points": 0,
        "in_dreamteam": 0,
        "dreamteam_count": 0,
        "selected_by_percent": 0,
        "transfers_in": 0,
        "transfers_in_event": 0,
        "transfers_out": 0,
        "transfers_out_event": 0,
    },
    "rank": {
        "selected_rank": 0,
        "selected_rank_type": "",
        "influence_rank": 0,
        "influence_rank_type": "",
        "creativity_rank": 0,
        "creativity_rank_type": "",
        "threat_rank": 0,
        "threat_rank_type": "",
        "ict_index_rank": 0,
        "ict_index_rank_type": "",
        "now_cost_rank": 0,
        "now_cost_rank_type": "",
        "form_rank": 0,
        "form_rank_type": "",
    },
    "expected": {
        "expected_goals": 0,
        "expected_assists": 0,
        "expected_goal_involvements": 0,
        "expected_goals_conceded": 0,
        "ep_next": 0,
        "ep_this": 0,
    },
    "stats_per_90": {
        "points_per_game_rank": 0,
        "points_per_game_rank_type": "",
        "starts_per_90": 0,
        "clean_sheets_per_90": 0,
        "defensive_contribution_per_90": 0,
        "expected_goals_per_90": 0,
        "saves_per_90": 0,
        "expected_assists_per_90": 0,
        "expected_goal_involvements_per_90": 0,
        "expected_goals_conceded_per_90": 0,
        "goals_conceded_per_90": 0,
        "points_per_game": 0,
    },
    #"history": [PLAYER_FIXTURES],
    #"past_years": [PLAYER_HISTORY],
}
PLAYER_HISTORY = {
    "season_name": "0",
    "element_code": "0",
    "start_cost": "0",
    "end_cost": "0",
    "total_points": "0",
    "minutes": "0",
    "goals_scored": "0",
    "assists": "0",
    "clean_sheets": "0",
    "goals_conceded": "0",
    "own_goals": "0",
    "penalties_saved": "0",
    "penalties_missed": "0",
    "yellow_cards": "0",
    "red_cards": "0",
    "saves": "0",
    "bonus": "0",
    "bps": "0",
    "influence": "0",
    "creativity": "0",
    "threat": "0",
    "ict_index": "0",
    "clearances_blocks_interceptions": "0",
    "recoveries": "0",
    "tackles": "0",
    "defensive_contribution": "0",
    "starts": "0",
    "expected_goals": "0",
    "expected_assists": "0",
    "expected_goal_involvements": "0",
    "expected_goals_conceded": "0"
}

PLAYER_FIXTURES = {
    "element": "0",
    "fixture": "0",
    "opponent_team": "0",
    "total_points": "0",
    "was_home": "0",
    "kickoff_time": "0",
    "team_h_score": "0",
    "team_a_score": "0",
    "round": "0",
    "modified": "0",
    "minutes": "0",
    "goals_scored": "0",
    "assists": "0",
    "clean_sheets": "0",
    "goals_conceded": "0",
    "own_goals": "0",
    "penalties_saved": "0",
    "penalties_missed": "0",
    "yellow_cards": "0",
    "red_cards": "0",
    "saves": "0",
    "bonus": "0",
    "bps": "0",
    "influence": "0",
    "creativity": "0",
    "threat": "0",
    "ict_index": "0",
    "clearances_blocks_interceptions": "0",
    "recoveries": "0",
    "tackles": "0",
    "defensive_contribution": "0",
    "starts": "0",
    "expected_goals": "0",
    "expected_assists": "0",
    "expected_goal_involvements": "0",
    "expected_goals_conceded": "0",
    "value": "0",
    "transfers_balance": "0",
    "selected": "0",
    "transfers_in": "0",
    "transfers_out": "0"
}
