# The Translator
FOTMOB_NAME_MAP = {
    "Man Utd": "Man United",
    "Nott'm Forest": "Nottm Forest",
    "Spurs": "Tottenham",
}

# Teams & Players keys
TEAMS_KEYS = [
    "win",
    "draw",
    "loss",
    "played",
    "points",
    "position",
    "form",
    "fotmob_rating",
    "goals_per_match",
    "goals_conceded_per_match",
    "average_possession",
    "clean_sheets",
    "expected_goals_xg",
    "xg_difference",
    "shots_on_target_per_match",
    "big_chances",
    "big_chances_missed",
    "accurate_passes_per_match",
    "accurate_long_balls_per_match",
    "accurate_crosses_per_match",
    "penalties_awarded",
    "touches_in_opposition_box",
    "corners",
    "set_piece_goals",
    "xg_conceded",
    "interceptions_per_match",
    "tackles_per_match",
    "clearances_per_match",
    "possession_won_final_3rd_per_match",
    "set_piece_goals_conceded",
    "penalties_conceded",
    "saves_per_match",
    "fouls_per_match",
    "yellow_cards",
    "red_cards",
    "strength",
    "strength_overall_home",
    "strength_overall_away",
    "strength_attack_home",
    "strength_attack_away",
    "strength_defence_home",
    "strength_defence_away",
]

PLAYERS_KEYS = []
